# Generated by Django 5.0.6 on 2024-07-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isStaff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isSuperuser',
            new_name='is_superuser',
        ),
    ]
